# Generated by Django 5.2.5 on 2025-10-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='quantity_changed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='action',
            field=models.CharField(choices=[('ADD', 'Add'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=50),
        ),
    ]
